FROM dr.prod.modcloth.com/build-essential:0.1.0
MAINTAINER Dan Buch <d.buch@modcloth.com>

RUN apt-get install -yq python-software-properties
RUN apt-add-repository ppa:brightbox/ruby-ng-experimental && apt-get update -yq
